<a href="https://colab.research.google.com/github/IgorNascimentoDEV/Analise-dados/blob/main/Curso_de_Python_SINAN_Script.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importação de bibliotecas

Após instaada a biblioteca temos que importar a biblioteca que iremos utilizar neste primeiro momento.
1.   Pandas - biblioteca padrão para análise de dados no Phthon

In [1]:
import pandas as pd

**OBS: a célula abaixo é necessária para que ossamos visualizar toda a tabela na tela**

In [2]:
pd.options.display.max_columns = None

A biblioteca Pandas será usada para transforma o arquivo CSV em uma tabea legível.

In [3]:
dados =  pd.read_csv('/content/drive/MyDrive/Arquivos para curso de python/dados animais/ANIMBR17.csv', encoding='latin1')
dados

<ipython-input-3-b0cc7392b1b2>:1: DtypeWarning: Columns (10,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  dados =  pd.read_csv('/content/drive/MyDrive/Arquivos para curso de python/dados animais/ANIMBR17.csv', encoding='latin1')

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA
0,2,X29,20170101,201701,2017,29,291080,1381.0,20170101,201701,2012.0,4004,M,6.0,2.0,10.0,29.0,291080.0,NaN,1.0,20170101,NaN,20170101,29.0,291080.0,NaN,9.0,6.0,1.0,9.0,1.0,9.0,9.0,9.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,9.0,9.0,0,0,0,0,0,0,0,0,0,9.0,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,9.0,1.0,,20170202,20170209
1,2,X29,20170101,201701,2017,35,352620,1335.0,20170101,201701,1980.0,4036,F,9.0,9.0,9.0,35.0,352620.0,NaN,1.0,20170101,NaN,20170101,35.0,352620.0,NaN,1.0,9.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,9.0,NaN,9.0,9.0,0,0,0,0,0,0,0,0,0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,,20170102,20170116
2,2,X29,20170101,201701,2017,13,130360,5584.0,20160515,201620,1990.0,4025,F,5.0,5.0,0.0,13.0,130360.0,NaN,1.0,20170101,612005.0,20160115,13.0,130360.0,NaN,5.0,9.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1.0,2.0,1.0,1.0,2.0,2.0,2.0,NaN,9.0,1.0,NaN,1.0,NaN,NaN,3.0,1.0,8,0,0,0,0,0,0,0,0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170101,20170125
3,2,X29,20170101,201701,2017,41,412010,1357.0,20170101,201701,1954.0,4062,F,5.0,1.0,6.0,41.0,411770.0,NaN,1.0,20170101,999993.0,20170101,41.0,412010.0,NaN,1.0,9.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170213,20170217
4,2,X29,20170101,201701,2017,26,261160,1497.0,20170101,201701,2013.0,4003,F,6.0,9.0,10.0,26.0,260840.0,NaN,1.0,20170101,NaN,20170101,26.0,260840.0,NaN,1.0,9.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170102,20170328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,2,X29,20171231,201801,2017,22,221050,NaN,20171231,201801,2006.0,4011,M,6.0,4.0,3.0,22.0,220060.0,NaN,1.0,20171231,999991.0,20171231,22.0,220060.0,NaN,1.0,9.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20171231,20180117
222854,2,X29,20171231,201801,2017,22,221050,NaN,20171231,201801,1982.0,4035,F,5.0,4.0,3.0,22.0,221050.0,NaN,1.0,20171231,999992.0,20171231,22.0,221050.0,NaN,1.0,4.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20171231,20180117
222855,2,X29,20171231,201801,2017,31,311680,1450.0,20171231,201801,1962.0,4055,M,6.0,4.0,1.0,31.0,310620.0,NaN,1.0,20171231,782305.0,20171231,31.0,311680.0,NaN,2.0,10.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,1.0,NaN,NaN,1.0,1.0,3,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,NaN,,20180129,20180129
222856,2,X29,20171231,201801,2017,41,410180,1356.0,20171230,201752,1972.0,4045,F,5.0,1.0,9.0,41.0,410180.0,NaN,1.0,20171231,NaN,20171230,41.0,410180.0,NaN,5.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,2.0,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20180210,20180810
222857,2,X29,20171231,201801,2017,29,293330,1398.0,20171231,201801,1998.0,4019,F,9.0,1.0,NaN,29.0,290120.0,NaN,1.0,20171231,NaN,20171231,29.0,290120.0,NaN,NaN,10.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,NaN,2.0,1.0,0,0,0,8,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,,,20191018

### Conversão baseado no Dicionário de Dados do SINAN
Quais colunas vamos manter?


Vamos pegar a lista de colunas que temos na nossa tabela, utilizando o comando **.columns** depois da nossa tabela.

In [4]:
dados.columns

Index(['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT',
       'ID_MUNICIP', 'ID_REGIONA', 'DT_SIN_PRI', 'SEM_PRI', 'ANO_NASC',
       'NU_IDADE_N', 'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF',
       'ID_MN_RESI', 'ID_RG_RESI', 'ID_PAIS', 'DT_INVEST', 'ID_OCUPA_N',
       'ANT_DT_ACI', 'ANT_UF', 'ANT_MUNIC_', 'ANT_LOCALI', 'ANT_TEMPO_',
       'ANT_LOCA_1', 'MCLI_LOCAL', 'CLI_DOR', 'CLI_EDEMA', 'CLI_EQUIMO',
       'CLI_NECROS', 'CLI_LOCAL_', 'CLI_LOCA_1', 'MCLI_SIST', 'CLI_NEURO',
       'CLI_HEMORR', 'CLI_VAGAIS', 'CLI_MIOLIT', 'CLI_RENAL', 'CLI_OUTR_2',
       'CLI_OUTR_3', 'CLI_TEMPO_', 'TP_ACIDENT', 'ANI_TIPO_1', 'ANI_SERPEN',
       'ANI_ARANHA', 'ANI_LAGART', 'TRA_CLASSI', 'CON_SOROTE', 'NU_AMPOLAS',
       'NU_AMPOL_1', 'NU_AMPOL_8', 'NU_AMPOL_6', 'NU_AMPOL_4', 'NU_AMPO_7',
       'NU_AMPO_5', 'NU_AMPOL_9', 'NU_AMPOL_3', 'COM_LOC', 'COM_SECUND',
       'COM_NECROS', 'COM_COMPOR', 'COM_DEFICT', 'COM_APUTAC', 'COM_SISTEM',
       'COM_RENAL', 'COM_EDEMA', 'COM_SEPTIC', 'COM_CHOQUE', 'DOENCA_TRA',
       'EVOLUCAO', 'DT_OBITO', 'DT_ENCERRA', 'DT_DIGITA'],
      dtype='object')

Dentre as colunas acima, devemos escolher quais devemos manter, copiando a lista gerada na célula anterior, ee apagando o nome daquelas que ão queremos.

In [5]:
colunas_manter = ['DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT',
       'ID_MUNICIP', 'ID_REGIONA', 'DT_SIN_PRI', 'SEM_PRI', 'ANO_NASC',
       'NU_IDADE_N', 'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF',
       'ID_MN_RESI', 'ID_RG_RESI', 'ID_PAIS', 'DT_INVEST', 'ID_OCUPA_N',
       'ANT_DT_ACI', 'ANT_UF', 'ANT_MUNIC_', 'ANT_LOCALI', 'ANT_TEMPO_',
       'ANT_LOCA_1', 'MCLI_LOCAL', 'CLI_DOR', 'CLI_EDEMA', 'CLI_EQUIMO',
       'CLI_NECROS', 'CLI_LOCAL_', 'CLI_LOCA_1', 'MCLI_SIST', 'CLI_NEURO',
       'CLI_HEMORR', 'CLI_VAGAIS', 'CLI_MIOLIT', 'CLI_RENAL', 'CLI_OUTR_2',
       'CLI_OUTR_3', 'CLI_TEMPO_', 'TP_ACIDENT', 'ANI_TIPO_1', 'ANI_SERPEN',
       'ANI_ARANHA', 'ANI_LAGART', 'TRA_CLASSI', 'CON_SOROTE', 'NU_AMPOLAS',
       'NU_AMPOL_1', 'NU_AMPOL_8', 'NU_AMPOL_6', 'NU_AMPOL_4', 'NU_AMPO_7',
       'NU_AMPO_5', 'NU_AMPOL_9', 'NU_AMPOL_3', 'COM_LOC', 'COM_SECUND',
       'COM_NECROS', 'COM_COMPOR', 'COM_DEFICT', 'COM_APUTAC', 'COM_SISTEM',
       'COM_RENAL', 'COM_EDEMA', 'COM_SEPTIC', 'COM_CHOQUE', 'DOENCA_TRA',
       'EVOLUCAO', 'DT_OBITO', 'DT_ENCERRA', 'DT_DIGITA']

Assim, utilizamos esta lista entre colchetes, ao lado do nome da nossa tabela, atribuindo um novo nome, ou substituindo a mesma.

In [6]:
dados = dados[colunas_manter].reset_index(drop=True)

### Recodificação dos dados
Um dos grandes problemas dos arquivos DBF é a codificação das variáveis. Simplesmente abrir o arquivo não traz informações claras, pois acabamos tendo que recorrer ao dicionário de Dados daquele arquivo. Com o Python, conseguimos recodificar as colunas, escrevendo o dicionário de dados para cada uma. É um rabalho que leva algum tempo, porém, precisamos fazê-lo somente uma vez e depois já estará pronto.

Avaliando p dicionário de dados, percebemos que muitas variáveis apresentam apenas o **SIM** ou **NÃo**. Para essas, faremos apenas um mini dicionário e aplicaremos a funçãoo **REPLACE**, que vai substituir ps valores encontrados na tabela por aqueles vistos no dicionário.

Utilizaremos uma coluna como exemplo, e depois aplicamos para as demais.

In [7]:
dados['MCLI_LOCAL'] = dados['MCLI_LOCAL'].replace({1: 'Sim', 2:'Não', 9:'Ignorado'})

Agora, criaremos uma lista com as colunas que possuem codificação de **SIM/NÃO**, e aplicaremos uma das funções mais úteis do Python, oloop de repetição chamado **For**

Essa função nos permite aplicar diversas vezes a mesma peração, alterando apenas um parâmetro

In [8]:
colunas_sim_nao = ['MCLI_LOCAL', 'CLI_DOR', 'CLI_EDEMA', 'CLI_EQUIMO', 'CLI_NECROS', 'CLI_LOCAL_',
                   'MCLI_SIST', 'CLI_NEURO', 'CLI_HEMORR', 'CLI_VAGAIS', 'CLI_MIOLIT', 'CLI_RENAL',
                   'CLI_OUTR_2', 'CON_SOROTE', 'COM_LOC', 'COM_SECUND', 'COM_NECROS', 'COM_COMPOR',
                   'COM_DEFICT', 'COM_APUTAC', 'COM_SISTEM', 'COM_RENAL', 'COM_EDEMA', 'COM_SEPTIC',
                   'COM_CHOQUE', 'DOENCA_TRA']

for coluna in colunas_sim_nao:
  dados[coluna] = dados[coluna].replace({1: 'Sim', 2:'Não', 9:'Ignorado'})


dados

,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA
0,20170101,201701,2017,29,291080,1381.0,20170101,201701,2012.0,4004,M,6.0,2.0,10.0,29.0,291080.0,NaN,1.0,20170101,NaN,20170101,29.0,291080.0,NaN,9.0,6.0,Sim,Ignorado,Sim,Ignorado,Ignorado,Ignorado,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,9.0,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaN,NaN,NaN,Ignorado,1.0,,20170202,20170209
1,20170101,201701,2017,35,352620,1335.0,20170101,201701,1980.0,4036,F,9.0,9.0,9.0,35.0,352620.0,NaN,1.0,20170101,NaN,20170101,35.0,352620.0,NaN,1.0,9.0,Não,NaN,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,9.0,NaN,9.0,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,,20170102,20170116
2,20170101,201701,2017,13,130360,5584.0,20160515,201620,1990.0,4025,F,5.0,5.0,0.0,13.0,130360.0,NaN,1.0,20170101,612005.0,20160115,13.0,130360.0,NaN,5.0,9.0,Sim,Sim,Sim,Sim,Sim,Não,NaN,Sim,Não,Sim,Sim,Não,Não,Não,NaN,9.0,1.0,NaN,1.0,NaN,NaN,3.0,Sim,8,0,0,0,0,0,0,0,0,Sim,Sim,Sim,Não,Sim,Sim,Não,NaN,NaN,NaN,NaN,Não,1.0,,20170101,20170125
3,20170101,201701,2017,41,412010,1357.0,20170101,201701,1954.0,4062,F,5.0,1.0,6.0,41.0,411770.0,NaN,1.0,20170101,999993.0,20170101,41.0,412010.0,NaN,1.0,9.0,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,,20170213,20170217
4,20170101,201701,2017,26,261160,1497.0,20170101,201701,2013.0,4003,F,6.0,9.0,10.0,26.0,260840.0,NaN,1.0,20170101,NaN,20170101,26.0,260840.0,NaN,1.0,9.0,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,,20170102,20170328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,20171231,201801,2017,22,221050,NaN,20171231,201801,2006.0,4011,M,6.0,4.0,3.0,22.0,220060.0,NaN,1.0,20171231,999991.0,20171231,22.0,220060.0,NaN,1.0,9.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,,20171231,20180117
222854,20171231,201801,2017,22,221050,NaN,20171231,201801,1982.0,4035,F,5.0,4.0,3.0,22.0,221050.0,NaN,1.0,20171231,999992.0,20171231,22.0,221050.0,NaN,1.0,4.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,,20171231,20180117
222855,20171231,201801,2017,31,311680,1450.0,20171231,201801,1962.0,4055,M,6.0,4.0,1.0,31.0,310620.0,NaN,1.0,20171231,782305.0,20171231,31.0,311680.0,NaN,2.0,10.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,1.0,NaN,NaN,1.0,Sim,3,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,NaN,,20180129,20180129
222856,20171231,201801,2017,41,410180,1356.0,20171230,201752,1972.0,4045,F,5.0,1.0,9.0,41.0,410180.0,NaN,1.0,20171231,NaN,20171230,41.0,410180.0,NaN,5.0,1.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,2.0,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,,20180210,20180810
222857,20171231,201801,2017,29,293330,1398.0,20171231,201801,1998.0,4019,F,9.0,1.0,NaN,29.0,290120.0,NaN,1.0,20171231,NaN,20171231,29.0,290120.0,NaN,NaN,10.0,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,NaN,2.0,Sim,0,0,0,8,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,,,20191018

Algumas são do tipo DATA, então vamos alterar para este formato

In [9]:
colunas_data = ['DT_NOTIFIC', 'DT_SIN_PRI',
                'DT_INVEST', 'DT_OBITO', 'DT_ENCERRA',
                'DT_DIGITA', 'ANT_DT_ACI']

for coluna in colunas_data:
  dados[coluna] = pd.to_datetime(dados[coluna], format='%Y%m%d', errors='coerce')


dados

,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA
0,2017-01-01,201701,2017,29,291080,1381.0,2017-01-01,201701,2012.0,4004,M,6.0,2.0,10.0,29.0,291080.0,NaN,1.0,2017-01-01,NaN,2017-01-01,29.0,291080.0,NaN,9.0,6.0,Sim,Ignorado,Sim,Ignorado,Ignorado,Ignorado,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,9.0,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaN,NaN,NaN,Ignorado,1.0,NaT,2017-02-02,2017-02-09
1,2017-01-01,201701,2017,35,352620,1335.0,2017-01-01,201701,1980.0,4036,F,9.0,9.0,9.0,35.0,352620.0,NaN,1.0,2017-01-01,NaN,2017-01-01,35.0,352620.0,NaN,1.0,9.0,Não,NaN,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,9.0,NaN,9.0,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaT,2017-01-02,2017-01-16
2,2017-01-01,201701,2017,13,130360,5584.0,2016-05-15,201620,1990.0,4025,F,5.0,5.0,0.0,13.0,130360.0,NaN,1.0,2017-01-01,612005.0,2016-01-15,13.0,130360.0,NaN,5.0,9.0,Sim,Sim,Sim,Sim,Sim,Não,NaN,Sim,Não,Sim,Sim,Não,Não,Não,NaN,9.0,1.0,NaN,1.0,NaN,NaN,3.0,Sim,8,0,0,0,0,0,0,0,0,Sim,Sim,Sim,Não,Sim,Sim,Não,NaN,NaN,NaN,NaN,Não,1.0,NaT,2017-01-01,2017-01-25
3,2017-01-01,201701,2017,41,412010,1357.0,2017-01-01,201701,1954.0,4062,F,5.0,1.0,6.0,41.0,411770.0,NaN,1.0,2017-01-01,999993.0,2017-01-01,41.0,412010.0,NaN,1.0,9.0,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,NaT,2017-02-13,2017-02-17
4,2017-01-01,201701,2017,26,261160,1497.0,2017-01-01,201701,2013.0,4003,F,6.0,9.0,10.0,26.0,260840.0,NaN,1.0,2017-01-01,NaN,2017-01-01,26.0,260840.0,NaN,1.0,9.0,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,NaT,2017-01-02,2017-03-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,2017-12-31,201801,2017,22,221050,NaN,2017-12-31,201801,2006.0,4011,M,6.0,4.0,3.0,22.0,220060.0,NaN,1.0,2017-12-31,999991.0,2017-12-31,22.0,220060.0,NaN,1.0,9.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,NaT,2017-12-31,2018-01-17
222854,2017-12-31,201801,2017,22,221050,NaN,2017-12-31,201801,1982.0,4035,F,5.0,4.0,3.0,22.0,221050.0,NaN,1.0,2017-12-31,999992.0,2017-12-31,22.0,221050.0,NaN,1.0,4.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,NaT,2017-12-31,2018-01-17
222855,2017-12-31,201801,2017,31,311680,1450.0,2017-12-31,201801,1962.0,4055,M,6.0,4.0,1.0,31.0,310620.0,NaN,1.0,2017-12-31,782305.0,2017-12-31,31.0,311680.0,NaN,2.0,10.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,1.0,NaN,NaN,1.0,Sim,3,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,NaN,NaT,2018-01-29,2018-01-29
222856,2017-12-31,201801,2017,41,410180,1356.0,2017-12-30,201752,1972.0,4045,F,5.0,1.0,9.0,41.0,410180.0,NaN,1.0,2017-12-31,NaN,2017-12-30,41.0,410180.0,NaN,5.0,1.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,2.0,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,NaT,2018-02-10,2018-08-10
222857,2017-12-31,201801,2017,29,293330,1398.0,2017-12-31,201801,1998.0,4019,F,9.0,1.0,NaN,29.0,290120.0,NaN,1.0,2017-12-31,NaN,2017-12-31,29.0,290120.0,NaN,NaN,10.0,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,NaN,2.0,Sim,0,0,0,8,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaT,NaT,2019-10-18

In [10]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222858 entries, 0 to 222857
Data columns (total 74 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   DT_NOTIFIC  222858 non-null  datetime64[ns]
 1   SEM_NOT     222858 non-null  int64
 2   NU_ANO      222858 non-null  int64
 3   SG_UF_NOT   222858 non-null  int64
 4   ID_MUNICIP  222858 non-null  int64
 5   ID_REGIONA  212929 non-null  float64
 6   DT_SIN_PRI  222858 non-null  datetime64[ns]
 7   SEM_PRI     222858 non-null  int64
 8   ANO_NASC    219324 non-null  object
 9   NU_IDADE_N  222858 non-null  int64
 10  CS_SEXO     222858 non-null  object
 11  CS_GESTANT  222851 non-null  float64
 12  CS_RACA     219292 non-null  float64
 13  CS_ESCOL_N  199978 non-null  float64
 14  SG_UF       222784 non-null  float64
 15  ID_MN_RESI  222784 non-null  float64
 16  ID_RG_RESI  0 non-null       float64
 17  ID_PAIS     222857 non-null  float64
 18  DT_INVEST   222858 non-null  datetime64[ns]
 19  ID_OCUPA_N  113134 non-null  object
 20  ANT_DT_ACI  222849 non-null  datetime64[ns]
 21  ANT_UF      222849 non-null  float64
 22  ANT_MUNIC_  222849 non-null  float64
 23  ANT_LOCALI  0 non-null       float64
 24  ANT_TEMPO_  216993 non-null  float64
 25  ANT_LOCA_1  222849 non-null  float64
 26  MCLI_LOCAL  221008 non-null  object
 27  CLI_DOR     207069 non-null  object
 28  CLI_EDEMA   207061 non-null  object
 29  CLI_EQUIMO  207041 non-null  object
 30  CLI_NECROS  207040 non-null  object
 31  CLI_LOCAL_  207027 non-null  object
 32  CLI_LOCA_1  26503 non-null   object
 33  MCLI_SIST   218133 non-null  object
 34  CLI_NEURO   15495 non-null   object
 35  CLI_HEMORR  15495 non-null   object
 36  CLI_VAGAIS  15495 non-null   object
 37  CLI_MIOLIT  15494 non-null   object
 38  CLI_RENAL   15494 non-null   object
 39  CLI_OUTR_2  15493 non-null   object
 40  CLI_OUTR_3  6844 non-null    object
 41  CLI_TEMPO_  195157 non-null  float64
 42  TP_ACIDENT  222849 non-null  float64
 43  ANI_TIPO_1  9279 non-null    object
 44  ANI_SERPEN  28738 non-null   float64
 45  ANI_ARANHA  33112 non-null   float64
 46  ANI_LAGART  5164 non-null    float64
 47  TRA_CLASSI  218123 non-null  float64
 48  CON_SOROTE  222849 non-null  object
 49  NU_AMPOLAS  222858 non-null  int64
 50  NU_AMPOL_1  222858 non-null  int64
 51  NU_AMPOL_8  222858 non-null  int64
 52  NU_AMPOL_6  222858 non-null  int64
 53  NU_AMPOL_4  222858 non-null  int64
 54  NU_AMPO_7   222858 non-null  int64
 55  NU_AMPO_5   222858 non-null  int64
 56  NU_AMPOL_9  222858 non-null  int64
 57  NU_AMPOL_3  222858 non-null  int64
 58  COM_LOC     209695 non-null  object
 59  COM_SECUND  2669 non-null    object
 60  COM_NECROS  2666 non-null    object
 61  COM_COMPOR  2666 non-null    object
 62  COM_DEFICT  2665 non-null    object
 63  COM_APUTAC  2665 non-null    object
 64  COM_SISTEM  207942 non-null  object
 65  COM_RENAL   853 non-null     object
 66  COM_EDEMA   852 non-null     object
 67  COM_SEPTIC  852 non-null     object
 68  COM_CHOQUE  852 non-null     object
 69  DOENCA_TRA  212492 non-null  object
 70  EVOLUCAO    211354 non-null  float64
 71  DT_OBITO    216 non-null     datetime64[ns]
 72  DT_ENCERRA  217816 non-null  datetime64[ns]
 73  DT_DIGITA   222858 non-null  datetime64[ns]
dtypes: datetime64[ns](7), float64(20), int64(15), object(32)
memory usage: 125.8+ MB

Agora vem a parte mais  trabalhoosa, onde temos que reescrever todas as codificações do dicionário de dados.
Em outras palaavras, criaremos vários dicionários a partir do dicionário do SINAN

In [11]:


dados['ANT_TEMPO_'] = dados['ANT_TEMPO_'].replace({1:'0 - 1h',
                                                   2:'1 - 3h',
                                                   3:'3 - 6h',
                                                   4:'6 - 12h',
                                                   5:'12 e 24h',
                                                   6:'24 e +h',
                                                   9:'Ignorado'})

dados['ANT_LOCA_1'] = dados['ANT_LOCA_1'].replace({1 : 'Cabeça',
                                                   2 : 'Braço',
                                                   3 : 'Ante-Braço',
                                                   4 : 'Mão',
                                                   5 : 'Dedo da Mão',
                                                   6 : 'tronco',
                                                   7 : 'Coxa',
                                                   8 : 'Perna',
                                                   9 : 'Pé',
                                                   10 : 'Dedo do Pé',
                                                   99 : 'Ignorado' })

dados['CLI_TEMPO_'] = dados['CLI_TEMPO_'].replace({1 : 'Normal',
                                                   2 : 'Alterado',
                                                   9 : 'Não realizado'})

dados['TP_ACIDENT'] = dados['TP_ACIDENT'].replace({1 : 'Serpente',
                                                   2 : 'Aranha',
                                                   3 : 'Escorpião',
                                                   4 : 'Lagarta',
                                                   5 : 'Abelha',
                                                   6 : 'Outros',
                                                   9 : 'Ignorado' })

dados['ANI_SERPEN'] = dados['ANI_SERPEN'].replace({1 : 'Botrópico',
                                                   2 : 'Crotálico',
                                                   3 : 'Elapídico',
                                                   4 : 'Laquético',
                                                   5 : 'Serpente não peçonhenta',
                                                   9 : 'Ignorado' })

dados['ANI_ARANHA'] = dados['ANI_ARANHA'].replace({1 : 'Foneutrismo',
                                                   2 : 'Loxoscelismo',
                                                   3 : 'Latroectismo',
                                                   4 : 'Outra aranha',
                                                   9 : 'Ignorado' })

dados['ANI_LAGART'] = dados['ANI_LAGART'].replace({1 : 'Lonomia',
                                                   2 : 'Outra lagarta',
                                                   9 : 'Ignorado'})

dados['TRA_CLASSI'] = dados['TRA_CLASSI'].replace({1 : 'Leve',
                                                   2 : 'Moderado',
                                                   3 : 'Grave',
                                                   9 : 'Ignorado'})

dados['EVOLUCAO'] = dados['EVOLUCAO'].replace({1 : 'Cura',
                                               2 : 'óbito por acidente por animais peçonhentos',
                                               3 : 'Óbito por outras causas',
                                               9 : 'Ignorado'})



dados['CS_GESTANT'] = dados['CS_GESTANT'].replace({1 : '1º Trimestre',
                                                   2 : '2º Trimestre',
                                                   3 : '3º Trimestre',
                                                   4 :'Idade gestacional ignorada',
                                                   5 : 'Não',
                                                   6 : 'Não se aplica',
                                                   9 : 'Ignorado' })

dados['CS_RACA'] = dados['CS_RACA'].replace({1 : 'branca',
                                             2 : 'preta',
                                             3 : 'amarela',
                                             4 : 'parda',
                                             5 : 'indígena',
                                             9 : 'Ignorado'})

A coluna Idade é um pouco diferente. O SINAN utiliza uma codificação neste formato: A composição da varável obedece o seguinte critério: primeiro dígito:

1.Hora

2.Dia

3.Mês

4.Ano


Exemplos:
  - 3009 - nove meses
  - 4018 - dezoito anos

Assim, como apenas nos interessa a idade em anos, diminuiremos todos os números por 4000, Caso o resutado seja negativo, deixamos como zero.

In [12]:
idades = []

for i in dados["NU_IDADE_N"]:
  if i > 4000:
    idades.append(i - 4000)
  elif 4000 > i :
    idades.append(0)
  else:
    idades.append(0)

dados["NU_IDADE_N_"] = idades

dados

,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA,NU_IDADE_N_
0,2017-01-01,201701,2017,29,291080,1381.0,2017-01-01,201701,2012.0,4004,M,Não se aplica,preta,10.0,29.0,291080.0,NaN,1.0,2017-01-01,NaN,2017-01-01,29.0,291080.0,NaN,Ignorado,tronco,Sim,Ignorado,Sim,Ignorado,Ignorado,Ignorado,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Ignorado,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaN,NaN,NaN,Ignorado,Cura,NaT,2017-02-02,2017-02-09,4
1,2017-01-01,201701,2017,35,352620,1335.0,2017-01-01,201701,1980.0,4036,F,Ignorado,Ignorado,9.0,35.0,352620.0,NaN,1.0,2017-01-01,NaN,2017-01-01,35.0,352620.0,NaN,0 - 1h,Pé,Não,NaN,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Aranha,NaN,NaN,Ignorado,NaN,Ignorado,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ignorado,NaT,2017-01-02,2017-01-16,36
2,2017-01-01,201701,2017,13,130360,5584.0,2016-05-15,201620,1990.0,4025,F,Não,indígena,0.0,13.0,130360.0,NaN,1.0,2017-01-01,612005.0,2016-01-15,13.0,130360.0,NaN,12 e 24h,Pé,Sim,Sim,Sim,Sim,Sim,Não,NaN,Sim,Não,Sim,Sim,Não,Não,Não,NaN,Não realizado,Serpente,NaN,Botrópico,NaN,NaN,Grave,Sim,8,0,0,0,0,0,0,0,0,Sim,Sim,Sim,Não,Sim,Sim,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-01-01,2017-01-25,25
3,2017-01-01,201701,2017,41,412010,1357.0,2017-01-01,201701,1954.0,4062,F,Não,branca,6.0,41.0,411770.0,NaN,1.0,2017-01-01,999993.0,2017-01-01,41.0,412010.0,NaN,0 - 1h,Pé,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-02-13,2017-02-17,62
4,2017-01-01,201701,2017,26,261160,1497.0,2017-01-01,201701,2013.0,4003,F,Não se aplica,Ignorado,10.0,26.0,260840.0,NaN,1.0,2017-01-01,NaN,2017-01-01,26.0,260840.0,NaN,0 - 1h,Pé,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-01-02,2017-03-28,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,2017-12-31,201801,2017,22,221050,NaN,2017-12-31,201801,2006.0,4011,M,Não se aplica,parda,3.0,22.0,220060.0,NaN,1.0,2017-12-31,999991.0,2017-12-31,22.0,220060.0,NaN,0 - 1h,Pé,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-12-31,2018-01-17,11
222854,2017-12-31,201801,2017,22,221050,NaN,2017-12-31,201801,1982.0,4035,F,Não,parda,3.0,22.0,221050.0,NaN,1.0,2017-12-31,999992.0,2017-12-31,22.0,221050.0,NaN,0 - 1h,Mão,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-12-31,2018-01-17,35
222855,2017-12-31,201801,2017,31,311680,1450.0,2017-12-31,201801,1962.0,4055,M,Não se aplica,parda,1.0,31.0,310620.0,NaN,1.0,2017-12-31,782305.0,2017-12-31,31.0,311680.0,NaN,1 - 3h,Dedo do Pé,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alterado,Serpente,NaN,Botrópico,NaN,NaN,Leve,Sim,3,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,NaN,NaT,2018-01-29,2018-01-29,55
222856,2017-12-31,201801,2017,41,410180,1356.0,2017-12-30,201752,1972.0,4045,F,Não,branca,9.0,41.0,410180.0,NaN,1.0,2017-12-31,NaN,2017-12-30,41.0,410180.0,NaN,12 e 24h,Cabeça,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Aranha,NaN,NaN,Loxoscelismo,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2018-02-10,2018-08-10,45
222857,2017-12-31,201801,2017,29,293330,1398.0,2017-12-31,201801,1998.0,4019,F,Ignorado,branca,NaN,29.0,290120.0,NaN,1.0,2017-12-31,NaN,2017-12-31,29.0,290120.0,NaN,NaN,Dedo do Pé,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Serpente,NaN,Laquético,NaN,NaN,Moderado,Sim,0,0,0,8,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaT,NaT,2019-10-18,19

**Código do IBGE para nome de município**

Da mesma maneira que utilizamos um dicionário e a função replace para alterar elementos no DataFrame, faremos o mesmo para transformar os códigos de IBGE em nomes de municípios, utilizando a função map.

Primeiramente, precisamos de uma tabela onde conversão já esteja pronta.

In [13]:
 municipios = pd.read_csv('https://raw.githubusercontent.com/andrejarenkow/Curso_SINAN_Udemy/main/dados/populacao%20ibge%206%20municipio%20br.csv')

municipios

       IBGE6                Municipio  populacao
0     110001    Alta Floresta D'Oeste      22945
1     110037  Alto Alegre dos Parecis      13241
2     110040             Alto Paraíso      21428
3     110034         Alvorada D'Oeste      14411
4     110002                Ariquemes     107863
...      ...                      ...        ...
5565  522200               Vianópolis      13863
5566  522205           Vicentinópolis       8743
5567  522220                 Vila Boa       6171
5568  522230            Vila Propício       5821
5569  530010                 Brasília    3015268

[5570 rows x 3 columns]

Porém, para convertê-lo em dicionário, precisamos realizar algumas alterações, como transformar o código do IBGE em tipo texxto (string), deixar apenas duas colunas (IBGE, e Municipio), e setar a coluna IBGE6 como index.

In [14]:
municipios = municipios[['IBGE6', 'Municipio']]

municipios = municipios.set_index('IBGE6')

municipios

                      Municipio
IBGE6
110001    Alta Floresta D'Oeste
110037  Alto Alegre dos Parecis
110040             Alto Paraíso
110034         Alvorada D'Oeste
110002                Ariquemes
...                         ...
522200               Vianópolis
522205           Vicentinópolis
522220                 Vila Boa
522230            Vila Propício
530010                 Brasília

[5570 rows x 1 columns]

Agora, basta utilizar a função **to_dict()** e teremos o nosso dicionário

In [15]:
dicionario_municipios = municipios.to_dict()['Municipio']

dicionario_municipios

{110001: "Alta Floresta D'Oeste",
 110037: 'Alto Alegre dos Parecis',
 110040: 'Alto Paraíso',
 110034: "Alvorada D'Oeste",
 110002: 'Ariquemes',
 110045: 'Buritis',
 110003: 'Cabixi',
 110060: 'Cacaulândia',
 110004: 'Cacoal',
 110070: 'Campo Novo de Rondônia',
 110080: 'Candeias do Jamari',
 110090: 'Castanheiras',
 110005: 'Cerejeiras',
 110092: 'Chupinguaia',
 110006: 'Colorado do Oeste',
 110007: 'Corumbiara',
 110008: 'Costa Marques',
 110094: 'Cujubim',
 110009: "Espigão D'Oeste",
 110100: 'Governador Jorge Teixeira',
 110010: 'Guajará-Mirim',
 110110: 'Itapuã do Oeste',
 110011: 'Jaru',
 110012: 'Ji-Paraná',
 110013: "Machadinho D'Oeste",
 110120: 'Ministro Andreazza',
 110130: 'Mirante da Serra',
 110140: 'Monte Negro',
 110014: "Nova Brasilândia D'Oeste",
 110033: 'Nova Mamoré',
 110143: 'Nova União',
 110050: 'Novo Horizonte do Oeste',
 110015: 'Ouro Preto do Oeste',
 110145: 'Parecis',
 110018: 'Pimenta Bueno',
 110146: 'Pimenteiras do Oeste',
 110020: 'Porto Velho',
 110025: 'Presidente Médici',
 110147: 'Primavera de Rondônia',
 110026: 'Rio Crespo',
 110028: 'Rolim de Moura',
 110029: "Santa Luzia D'Oeste",
 110148: "São Felipe D'Oeste",
 110149: 'São Francisco do Guaporé',
 110032: 'São Miguel do Guaporé',
 110150: 'Seringueiras',
 110155: 'Teixeirópolis',
 110160: 'Theobroma',
 110170: 'Urupá',
 110175: 'Vale do Anari',
 110180: 'Vale do Paraíso',
 110030: 'Vilhena',
 120001: 'Acrelândia',
 120005: 'Assis Brasil',
 120010: 'Brasiléia',
 120013: 'Bujari',
 120017: 'Capixaba',
 120020: 'Cruzeiro do Sul',
 120025: 'Epitaciolândia',
 120030: 'Feijó',
 120032: 'Jordão',
 120033: 'Mâncio Lima',
 120034: 'Manoel Urbano',
 120035: 'Marechal Thaumaturgo',
 120038: 'Plácido de Castro',
 120080: 'Porto Acre',
 120039: 'Porto Walter',
 120040: 'Rio Branco',
 120042: 'Rodrigues Alves',
 120043: 'Santa Rosa do Purus',
 120050: 'Sena Madureira',
 120045: 'Senador Guiomard',
 120060: 'Tarauacá',
 120070: 'Xapuri',
 130002: 'Alvarães',
 130006: 'Amaturá',
 130008: 'Anamã',
 130010: 'Anori',
 130014: 'Apuí',
 130020: 'Atalaia do Norte',
 130030: 'Autazes',
 130040: 'Barcelos',
 130050: 'Barreirinha',
 130060: 'Benjamin Constant',
 130063: 'Beruri',
 130068: 'Boa Vista do Ramos',
 130070: 'Boca do Acre',
 130080: 'Borba',
 130083: 'Caapiranga',
 130090: 'Canutama',
 130100: 'Carauari',
 130110: 'Careiro',
 130115: 'Careiro da Várzea',
 130120: 'Coari',
 130130: 'Codajás',
 130140: 'Eirunepé',
 130150: 'Envira',
 130160: 'Fonte Boa',
 130165: 'Guajará',
 130170: 'Humaitá',
 130180: 'Ipixuna',
 130185: 'Iranduba',
 130190: 'Itacoatiara',
 130195: 'Itamarati',
 130200: 'Itapiranga',
 130210: 'Japurá',
 130220: 'Juruá',
 130230: 'Jutaí',
 130240: 'Lábrea',
 130250: 'Manacapuru',
 130255: 'Manaquiri',
 130260: 'Manaus',
 130270: 'Manicoré',
 130280: 'Maraã',
 130290: 'Maués',
 130300: 'Nhamundá',
 130310: 'Nova Olinda do Norte',
 130320: 'Novo Airão',
 130330: 'Novo Aripuanã',
 130340: 'Parintins',
 130350: 'Pauini',
 130353: 'Presidente Figueiredo',
 130356: 'Rio Preto da Eva',
 130360: 'Santa Isabel do Rio Negro',
 130370: 'Santo Antônio do Içá',
 130380: 'São Gabriel da Cachoeira',
 130390: 'São Paulo de Olivença',
 130395: 'São Sebastião do Uatumã',
 130400: 'Silves',
 130406: 'Tabatinga',
 130410: 'Tapauá',
 130420: 'Tefé',
 130423: 'Tonantins',
 130426: 'Uarini',
 130430: 'Urucará',
 130440: 'Urucurituba',
 140005: 'Alto Alegre',
 140002: 'Amajari',
 140010: 'Boa Vista',
 140015: 'Bonfim',
 140017: 'Cantá',
 140020: 'Caracaraí',
 140023: 'Caroebe',
 140028: 'Iracema',
 140030: 'Mucajaí',
 140040: 'Normandia',
 140045: 'Pacaraima',
 140047: 'Rorainópolis',
 140050: 'São João da Baliza',
 140060: 'São Luiz',
 140070: 'Uiramutã',
 150010: 'Abaetetuba',
 150013: 'Abel Figueiredo',
 150020: 'Acará',
 150030: 'Afuá',
 150034: 'Água Azul do Norte',
 150040: 'Alenquer',
 150050: 'Almeirim',
 150060: 'Altamira',
 150070: 'Anajás',
 150080: 'Ananindeua',
 150085: 'Anapu',
 150090: 'Augusto Corrêa',
 150095: 'Aurora do Pará',
 150100: 'Aveiro',
 150110: 'Bagre',
 150120: 'Baião',
 150125: 'Bannach',
 150130: 'Barcarena',
 150140: 'Belém',
 150145: 'Belterra',
 150150: 'Benevides',
 150157: 'Bom Jesus do Tocantins',
 150160: 'Bonito',
 150170: 'Bragança',
 150172: 'Brasil Novo',
 150175: 'Brejo Grande do Araguaia',
 150178: 'Breu Branco',
 150180: 'Breves',
 150190: 'Bujaru',
 150200: 'Cachoeira do Arari',
 150195: 'Cachoeira do Piriá',
 150210: 'Cametá',
 150215: 'Canaã dos Carajás',
 150220: 'Capanema',
 150230: 'Capitão Poço',
 150240: 'Castanhal',
 150250: 'Chaves',
 150260: 'Colares',
 150270: 'Conceição do Araguaia',
 150275: 'Concórdia do Pará',
 150276: 'Cumaru do Norte',
 150277: 'Curionópolis',
 150280: 'Curralinho',
 150285: 'Curuá',
 150290: 'Curuçá',
 150293: 'Dom Eliseu',
 150295: 'Eldorado do Carajás',
 150300: 'Faro',
 150304: 'Floresta do Araguaia',
 150307: 'Garrafão do Norte',
 150309: 'Goianésia do Pará',
 150310: 'Gurupá',
 150320: 'Igarapé-Açu',
 150330: 'Igarapé-Miri',
 150340: 'Inhangapi',
 150345: 'Ipixuna do Pará',
 150350: 'Irituia',
 150360: 'Itaituba',
 150370: 'Itupiranga',
 150375: 'Jacareacanga',
 150380: 'Jacundá',
 150390: 'Juruti',
 150400: 'Limoeiro do Ajuru',
 150405: 'Mãe do Rio',
 150410: 'Magalhães Barata',
 150420: 'Marabá',
 150430: 'Maracanã',
 150440: 'Marapanim',
 150442: 'Marituba',
 150445: 'Medicilândia',
 150450: 'Melgaço',
 150460: 'Mocajuba',
 150470: 'Moju',
 150475: 'Mojuí dos Campos',
 150480: 'Monte Alegre',
 150490: 'Muaná',
 150495: 'Nova Esperança do Piriá',
 150497: 'Nova Ipixuna',
 150500: 'Nova Timboteua',
 150503: 'Novo Progresso',
 150506: 'Novo Repartimento',
 150510: 'Óbidos',
 150520: 'Oeiras do Pará',
 150530: 'Oriximiná',
 150540: 'Ourém',
 150543: 'Ourilândia do Norte',
 150548: 'Pacajá',
 150549: 'Palestina do Pará',
 150550: 'Paragominas',
 150553: 'Parauapebas',
 150555: "Pau D'Arco",
 150560: 'Peixe-Boi',
 150563: 'Piçarra',
 150565: 'Placas',
 150570: 'Ponta de Pedras',
 150580: 'Portel',
 150590: 'Porto de Moz',
 150600: 'Prainha',
 150610: 'Primavera',
 150611: 'Quatipuru',
 150613: 'Redenção',
 150616: 'Rio Maria',
 150618: 'Rondon do Pará',
 150619: 'Rurópolis',
 150620: 'Salinópolis',
 150630: 'Salvaterra',
 150635: 'Santa Bárbara do Pará',
 150640: 'Santa Cruz do Arari',
 150650: 'Santa Izabel do Pará',
 150655: 'Santa Luzia do Pará',
 150658: 'Santa Maria das Barreiras',
 150660: 'Santa Maria do Pará',
 150670: 'Santana do Araguaia',
 150680: 'Santarém',
 150690: 'Santarém Novo',
 150700: 'Santo Antônio do Tauá',
 150710: 'São Caetano de Odivelas',
 150715: 'São Domingos do Araguaia',
 150720: 'São Domingos do Capim',
 150730: 'São Félix do Xingu',
 150740: 'São Francisco do Pará',
 150745: 'São Geraldo do Araguaia',
 150746: 'São João da Ponta',
 150747: 'São João de Pirabas',
 150750: 'São João do Araguaia',
 150760: 'São Miguel do Guamá',
 150770: 'São Sebastião da Boa Vista',
 150775: 'Sapucaia',
 150780: 'Senador José Porfírio',
 150790: 'Soure',
 150795: 'Tailândia',
 150796: 'Terra Alta',
 150797: 'Terra Santa',
 150800: 'Tomé-Açu',
 150803: 'Tracuateua',
 150805: 'Trairão',
 150808: 'Tucumã',
 150810: 'Tucuruí',
 150812: 'Ulianópolis',
 150815: 'Uruará',
 150820: 'Vigia',
 150830: 'Viseu',
 150835: 'Vitória do Xingu',
 150840: 'Xinguara',
 160010: 'Amapá',
 160020: 'Calçoene',
 160021: 'Cutias',
 160023: 'Ferreira Gomes',
 160025: 'Itaubal',
 160027: 'Laranjal do Jari',
 160030: 'Macapá',
 160040: 'Mazagão',
 160050: 'Oiapoque',
 160015: 'Pedra Branca do Amapari',
 160053: 'Porto Grande',
 160055: 'Pracuúba',
 160060: 'Santana',
 160005: 'Serra do Navio',
 160070: 'Tartarugalzinho',
 160080: 'Vitória do Jari',
 170025: 'Abreulândia',
 170030: 'Aguiarnópolis',
 170035: 'Aliança do Tocantins',
 170040: 'Almas',
 170070: 'Alvorada',
 170100: 'Ananás',
 170105: 'Angico',
 170110: 'Aparecida do Rio Negro',
 170130: 'Aragominas',
 170190: 'Araguacema',
 170200: 'Araguaçu',
 170210: 'Araguaína',
 170215: 'Araguanã',
 170220: 'Araguatins',
 170230: 'Arapoema',
 170240: 'Arraias',
 170255: 'Augustinópolis',
 170270: 'Aurora do Tocantins',
 170290: 'Axixá do Tocantins',
 170300: 'Babaçulândia',
 170305: 'Bandeirantes do Tocantins',
 170307: 'Barra do Ouro',
 170310: 'Barrolândia',
 170320: 'Bernardo Sayão',
 170330: 'Bom Jesus do Tocantins',
 170360: 'Brasilândia do Tocantins',
 170370: 'Brejinho de Nazaré',
 170380: 'Buriti do Tocantins',
 170382: 'Cachoeirinha',
 170384: 'Campos Lindos',
 170386: 'Cariri do Tocantins',
 170388: 'Carmolândia',
 170389: 'Carrasco Bonito',
 170390: 'Caseara',
 170410: 'Centenário',
 170510: 'Chapada da Natividade',
 170460: 'Chapada de Areia',
 170550: 'Colinas do Tocantins',
 171670: 'Colméia',
 170555: 'Combinado',
 170560: 'Conceição do Tocantins',
 170600: 'Couto Magalhães',
 170610: 'Cristalândia',
 170625: 'Crixás do Tocantins',
 170650: 'Darcinópolis',
 170700: 'Dianópolis',
 170710: 'Divinópolis do Tocantins',
 170720: 'Dois Irmãos do Tocantins',
 170730: 'Dueré',
 170740: 'Esperantina',
 170755: 'Fátima',
 170765: 'Figueirópolis',
 170770: 'Filadélfia',
 170820: 'Formoso do Araguaia',
 170825: 'Fortaleza do Tabocão',
 170830: 'Goianorte',
 170900: 'Goiatins',
 170930: 'Guaraí',
 170950: 'Gurupi',
 170980: 'Ipueiras',
 171050: 'Itacajá',
 171070: 'Itaguatins',
 171090: 'Itapiratins',
 171110: 'Itaporã do Tocantins',
 171150: 'Jaú do Tocantins',
 171180: 'Juarina',
 171190: 'Lagoa da Confusão',
 171195: 'Lagoa do Tocantins',
 171200: 'Lajeado',
 171215: 'Lavandeira',
 171240: 'Lizarda',
 171245: 'Luzinópolis',
 171250: 'Marianópolis do Tocantins',
 171270: 'Mateiros',
 171280: 'Maurilândia do Tocantins',
 171320: 'Miracema do Tocantins',
 171330: 'Miranorte',
 171360: 'Monte do Carmo',
 171370: 'Monte Santo do Tocantins',
 171395: 'Muricilândia',
 171420: 'Natividade',
 171430: 'Nazaré',
 171488: 'Nova Olinda',
 171500: 'Nova Rosalândia',
 171510: 'Novo Acordo',
 171515: 'Novo Alegre',
 171525: 'Novo Jardim',
 171550: 'Oliveira de Fátima',
 172100: 'Palmas',
 171570: 'Palmeirante',
 171380: 'Palmeiras do Tocantins',
 171575: 'Palmeirópolis',
 171610: 'Paraíso do Tocantins',
 171620: 'Paranã',
 171630: "Pau D'Arco",
 171650: 'Pedro Afonso',
 171660: 'Peixe',
 171665: 'Pequizeiro',
 171700: 'Pindorama do Tocantins',
 171720: 'Piraquê',
 171750: 'Pium',
 171780: 'Ponte Alta do Bom Jesus',
 171790: 'Ponte Alta do Tocantins',
 171800: 'Porto Alegre do Tocantins',
 171820: 'Porto Nacional',
 171830: 'Praia Norte',
 171840: 'Presidente Kennedy',
 171845: 'Pugmil',
 171850: 'Recursolândia',
 171855: 'Riachinho',
 171865: 'Rio da Conceição',
 171870: 'Rio dos Bois',
 171875: 'Rio Sono',
 171880: 'Sampaio',
 171884: 'Sandolândia',
 171886: 'Santa Fé do Araguaia',
 171888: 'Santa Maria do Tocantins',
 171889: 'Santa Rita do Tocantins',
 171890: 'Santa Rosa do Tocantins',
 171900: 'Santa Tereza do Tocantins',
 172000: 'Santa Terezinha do Tocantins',
 172010: 'São Bento do Tocantins',
 172015: 'São Félix do Tocantins',
 172020: 'São Miguel do Tocantins',
 172025: 'São Salvador do Tocantins',
 172030: 'São Sebastião do Tocantins',
 172049: 'São Valério',
 172065: 'Silvanópolis',
 172080: 'Sítio Novo do Tocantins',
 172085: 'Sucupira',
 172090: 'Taguatinga',
 172093: 'Taipas do Tocantins',
 172097: 'Talismã',
 172110: 'Tocantínia',
 172120: 'Tocantinópolis',
 172125: 'Tupirama',
 172130: 'Tupiratins',
 172208: 'Wanderlândia',
 172210: 'Xambioá',
 210005: 'Açailândia',
 210010: 'Afonso Cunha',
 210015: 'Água Doce do Maranhão',
 210020: 'Alcântara',
 210030: 'Aldeias Altas',
 210040: 'Altamira do Maranhão',
 210043: 'Alto Alegre do Maranhão',
 210047: 'Alto Alegre do Pindaré',
 210050: 'Alto Parnaíba',
 210055: 'Amapá do Maranhão',
 210060: 'Amarante do Maranhão',
 210070: 'Anajatuba',
 210080: 'Anapurus',
 210083: 'Apicum-Açu',
 210087: 'Araguanã',
 210090: 'Araioses',
 210095: 'Arame',
 210100: 'Arari',
 210110: 'Axixá',
 210120: 'Bacabal',
 210125: 'Bacabeira',
 210130: 'Bacuri',
 210135: 'Bacurituba',
 210140: 'Balsas',
 210150: 'Barão de Grajaú',
 210160: 'Barra do Corda',
 210170: 'Barreirinhas',
 210177: 'Bela Vista do Maranhão',
 210173: 'Belágua',
 210180: 'Benedito Leite',
 210190: 'Bequimão',
 210193: 'Bernardo do Mearim',
 210197: 'Boa Vista do Gurupi',
 210200: 'Bom Jardim',
 210203: 'Bom Jesus das Selvas',
 210207: 'Bom Lugar',
 210210: 'Brejo',
 210215: 'Brejo de Areia',
 210220: 'Buriti',
 210230: 'Buriti Bravo',
 210232: 'Buriticupu',
 210235: 'Buritirana',
 210237: 'Cachoeira Grande',
 210240: 'Cajapió',
 210250: 'Cajari',
 210255: 'Campestre do Maranhão',
 210260: 'Cândido Mendes',
 210270: 'Cantanhede',
 210275: 'Capinzal do Norte',
 210280: 'Carolina',
 210290: 'Carutapera',
 210300: 'Caxias',
 210310: 'Cedral',
 210312: 'Central do Maranhão',
 210315: 'Centro do Guilherme',
 210317: 'Centro Novo do Maranhão',
 210320: 'Chapadinha',
 210325: 'Cidelândia',
 210330: 'Codó',
 210340: 'Coelho Neto',
 210350: 'Colinas',
 210355: 'Conceição do Lago-Açu',
 210360: 'Coroatá',
 210370: 'Cururupu',
 210375: 'Davinópolis',
 210380: 'Dom Pedro',
 210390: 'Duque Bacelar',
 210400: 'Esperantinópolis',
 210405: 'Estreito',
 210407: 'Feira Nova do Maranhão',
 210408: 'Fernando Falcão',
 210409: 'Formosa da Serra Negra',
 210410: 'Fortaleza dos Nogueiras',
 210420: 'Fortuna',
 210430: 'Godofredo Viana',
 210440: 'Gonçalves Dias',
 210450: 'Governador Archer',
 210455: 'Governador Edison Lobão',
 210460: 'Governador Eugênio Barros',
 210462: 'Governador Luiz Rocha',
 210465: 'Governador Newton Bello',
 210467: 'Governador Nunes Freire',
 210470: 'Graça Aranha',
 210480: 'Grajaú',
 210490: 'Guimarães',
 210500: 'Humberto de Campos',
 210510: 'Icatu',
 210515: 'Igarapé do Meio',
 210520: 'Igarapé Grande',
 210530: 'Imperatriz',
 210535: 'Itaipava do Grajaú',
 210540: 'Itapecuru Mirim',
 210542: 'Itinga do Maranhão',
 210545: 'Jatobá',
 210547: 'Jenipapo dos Vieiras',
 210550: 'João Lisboa',
 210560: 'Joselândia',
 210565: 'Junco do Maranhão',
 210570: 'Lago da Pedra',
 210580: 'Lago do Junco',
 210594: 'Lago dos Rodrigues',
 210590: 'Lago Verde',
 210592: 'Lagoa do Mato',
 210596: 'Lagoa Grande do Maranhão',
 210598: 'Lajeado Novo',
 210600: 'Lima Campos',
 210610: 'Loreto',
 210620: 'Luís Domingues',
 210630: 'Magalhães de Almeida',
 210632: 'Maracaçumé',
 210635: 'Marajá do Sena',
 210637: 'Maranhãozinho',
 210640: 'Mata Roma',
 210650: 'Matinha',
 210660: 'Matões',
 210663: 'Matões do Norte',
 210667: 'Milagres do Maranhão',
 210670: 'Mirador',
 210675: 'Miranda do Norte',
 210680: 'Mirinzal',
 210690: 'Monção',
 210700: 'Montes Altos',
 210710: 'Morros',
 210720: 'Nina Rodrigues',
 210725: 'Nova Colinas',
 210730: 'Nova Iorque',
 210735: 'Nova Olinda do Maranhão',
 210740: "Olho d'Água das Cunhãs",
 210745: 'Olinda Nova do Maranhão',
 210750: 'Paço do Lumiar',
 210760: 'Palmeirândia',
 210770: 'Paraibano',
 210780: 'Parnarama',
 210790: 'Passagem Franca',
 210800: 'Pastos Bons',
 210805: 'Paulino Neves',
 210810: 'Paulo Ramos',
 210820: 'Pedreiras',
 210825: 'Pedro do Rosário',
 210830: 'Penalva',
 210840: 'Peri Mirim',
 210845: 'Peritoró',
 210850: 'Pindaré-Mirim',
 210860: 'Pinheiro',
 210870: 'Pio XII',
 210880: 'Pirapemas',
 210890: 'Poção de Pedras',
 210900: 'Porto Franco',
 210905: 'Porto Rico do Maranhão',
 210910: 'Presidente Dutra',
 210920: 'Presidente Juscelino',
 210923: 'Presidente Médici',
 210927: 'Presidente Sarney',
 210930: 'Presidente Vargas',
 210940: 'Primeira Cruz',
 210945: 'Raposa',
 210950: 'Riachão',
 210955: 'Ribamar Fiquene',
 210960: 'Rosário',
 210970: 'Sambaíba',
 210975: 'Santa Filomena do Maranhão',
 210980: 'Santa Helena',
 210990: 'Santa Inês',
 211000: 'Santa Luzia',
 211003: 'Santa Luzia do Paruá',
 211010: 'Santa Quitéria do Maranhão',
 211020: 'Santa Rita',
 211023: 'Santana do Maranhão',
 211027: 'Santo Amaro do Maranhão',
 211030: 'Santo Antônio dos Lopes',
 211040: 'São Benedito do Rio Preto',
 211050: 'São Bento',
 211060: 'São Bernardo',
 211065: 'São Domingos do Azeitão',
 211070: 'São Domingos do Maranhão',
 211080: 'São Félix de Balsas',
 211085: 'São Francisco do Brejão',
 211090: 'São Francisco do Maranhão',
 211100: 'São João Batista',
 211102: 'São João do Carú',
 211105: 'São João do Paraíso',
 211107: 'São João do Soter',
 211110: 'São João dos Patos',
 211120: 'São José de Ribamar',
 211125: 'São José dos Basílios',
 211130: 'São Luís',
 211140: 'São Luís Gonzaga do Maranhão',
 211150: 'São Mateus do Maranhão',
 211153: 'São Pedro da Água Branca',
 211157: 'São Pedro dos Crentes',
 211160: 'São Raimundo das Mangabeiras',
 211163: 'São Raimundo do Doca Bezerra',
 211167: 'São Roberto',
 211170: 'São Vicente Ferrer',
 211172: 'Satubinha',
 211174: 'Senador Alexandre Costa',
 211176: 'Senador La Rocque',
 211178: 'Serrano do Maranhão',
 211180: 'Sítio Novo',
 211190: 'Sucupira do Norte',
 211195: 'Sucupira do Riachão',
 211200: 'Tasso Fragoso',
 211210: 'Timbiras',
 211220: 'Timon',
 211223: 'Trizidela do Vale',
 211227: 'Tufilândia',
 211230: 'Tuntum',
 211240: 'Turiaçu',
 211245: 'Turilândia',
 211250: 'Tutóia',
 211260: 'Urbano Santos',
 211270: 'Vargem Grande',
 211280: 'Viana',
 211285: 'Vila Nova dos Martírios',
 211290: 'Vitória do Mearim',
 211300: 'Vitorino Freire',
 211400: 'Zé Doca',
 220005: 'Acauã',
 220010: 'Agricolândia',
 220020: 'Água Branca',
 220025: 'Alagoinha do Piauí',
 220027: 'Alegrete do Piauí',
 220030: 'Alto Longá',
 220040: 'Altos',
 220045: 'Alvorada do Gurguéia',
 220050: 'Amarante',
 220060: 'Angical do Piauí',
 220070: 'Anísio de Abreu',
 220080: 'Antônio Almeida',
 220090: 'Aroazes',
 220095: 'Aroeiras do Itaim',
 220100: 'Arraial',
 220105: 'Assunção do Piauí',
 220110: 'Avelino Lopes',
 220115: 'Baixa Grande do Ribeiro',
 220117: "Barra D'Alcântara",
 220120: 'Barras',
 220130: 'Barreiras do Piauí',
 220140: 'Barro Duro',
 220150: 'Batalha',
 220155: 'Bela Vista do Piauí',
 220157: 'Belém do Piauí',
 220160: 'Beneditinos',
 220170: 'Bertolínia',
 220173: 'Betânia do Piauí',
 220177: 'Boa Hora',
 220180: 'Bocaina',
 220190: 'Bom Jesus',
 220191: 'Bom Princípio do Piauí',
 220192: 'Bonfim do Piauí',
 220194: 'Boqueirão do Piauí',
 220196: 'Brasileira',
 220198: 'Brejo do Piauí',
 220200: 'Buriti dos Lopes',
 220202: 'Buriti dos Montes',
 220205: 'Cabeceiras do Piauí',
 220207: 'Cajazeiras do Piauí',
 220208: 'Cajueiro da Praia',
 220209: 'Caldeirão Grande do Piauí',
 220210: 'Campinas do Piauí',
 220211: 'Campo Alegre do Fidalgo',
 220213: 'Campo Grande do Piauí',
 220217: 'Campo Largo do Piauí',
 220220: 'Campo Maior',
 220225: 'Canavieira',
 220230: 'Canto do Buriti',
 220240: 'Capitão de Campos',
 220245: 'Capitão Gervásio Oliveira',
 220250: 'Caracol',
 220253: 'Caraúbas do Piauí',
 220255: 'Caridade do Piauí',
 220260: 'Castelo do Piauí',
 220265: 'Caxingó',
 220270: 'Cocal',
 220271: 'Cocal de Telha',
 220272: 'Cocal dos Alves',
 220273: 'Coivaras',
 220275: 'Colônia do Gurguéia',
 220277: 'Colônia do Piauí',
 220280: 'Conceição do Canindé',
 220285: 'Coronel José Dias',
 220290: 'Corrente',
 220300: 'Cristalândia do Piauí',
 220310: 'Cristino Castro',
 220320: 'Curimatá',
 220323: 'Currais',
 220327: 'Curral Novo do Piauí',
 220325: 'Curralinhos',
 220330: 'Demerval Lobão',
 220335: 'Dirceu Arcoverde',
 220340: 'Dom Expedito Lopes',
 220345: 'Dom Inocêncio',
 220342: 'Domingos Mourão',
 220350: 'Elesbão Veloso',
 220360: 'Eliseu Martins',
 220370: 'Esperantina',
 220375: 'Fartura do Piauí',
 220380: 'Flores do Piauí',
 220385: 'Floresta do Piauí',
 220390: 'Floriano',
 220400: 'Francinópolis',
 220410: 'Francisco Ayres',
 220415: 'Francisco Macedo',
 220420: 'Francisco Santos',
 220430: 'Fronteiras',
 220435: 'Geminiano',
 220440: 'Gilbués',
 220450: 'Guadalupe',
 220455: 'Guaribas',
 220460: 'Hugo Napoleão',
 220465: 'Ilha Grande',
 220470: 'Inhuma',
 220480: 'Ipiranga do Piauí',
 220490: 'Isaías Coelho',
 220500: 'Itainópolis',
 220510: 'Itaueira',
 220515: 'Jacobina do Piauí',
 220520: 'Jaicós',
 220525: 'Jardim do Mulato',
 220527: 'Jatobá do Piauí',
 220530: 'Jerumenha',
 220535: 'João Costa',
 220540: 'Joaquim Pires',

Para trannsformar os dados, agora vamos utilizar a função map. Pode surgir a dúvida: "**Por que aqui utilizamos o map e antes utilizamos o replace? Existe diferença?**"


Respondendo: O map é uma função que, caso o valor não esteja no dicionário, ele se transforma em NaN, fazendo com que percamos aquele dado, porém, ela é 60 vezes mais rápidado que o replace, então ganhamos tempo quando o dicionário possui mais de 5000 valores.

Assim, convertemos as duas colunas que onde temos os códiigos do IBGE(ID_MUNICIP, ID_MN_RESI e ANT_MUNIC_).

In [19]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222858 entries, 0 to 222857
Data columns (total 75 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DT_NOTIFIC   222858 non-null  datetime64[ns]
 1   SEM_NOT      222858 non-null  int64
 2   NU_ANO       222858 non-null  int64
 3   SG_UF_NOT    222858 non-null  int64
 4   ID_MUNICIP   222858 non-null  int64
 5   ID_REGIONA   212929 non-null  float64
 6   DT_SIN_PRI   222858 non-null  datetime64[ns]
 7   SEM_PRI      222858 non-null  int64
 8   ANO_NASC     219324 non-null  object
 9   NU_IDADE_N   222858 non-null  int64
 10  CS_SEXO      222858 non-null  object
 11  CS_GESTANT   222851 non-null  object
 12  CS_RACA      219292 non-null  object
 13  CS_ESCOL_N   199978 non-null  float64
 14  SG_UF        222784 non-null  float64
 15  ID_MN_RESI   222784 non-null  float64
 16  ID_RG_RESI   0 non-null       float64
 17  ID_PAIS      222857 non-null  float64
 18  DT_INVEST    222858 non-null  datetime64[ns]
 19  ID_OCUPA_N   113134 non-null  object
 20  ANT_DT_ACI   222849 non-null  datetime64[ns]
 21  ANT_UF       222849 non-null  float64
 22  ANT_MUNIC_   222849 non-null  float64
 23  ANT_LOCALI   0 non-null       float64
 24  ANT_TEMPO_   216993 non-null  object
 25  ANT_LOCA_1   222849 non-null  object
 26  MCLI_LOCAL   221008 non-null  object
 27  CLI_DOR      207069 non-null  object
 28  CLI_EDEMA    207061 non-null  object
 29  CLI_EQUIMO   207041 non-null  object
 30  CLI_NECROS   207040 non-null  object
 31  CLI_LOCAL_   207027 non-null  object
 32  CLI_LOCA_1   26503 non-null   object
 33  MCLI_SIST    218133 non-null  object
 34  CLI_NEURO    15495 non-null   object
 35  CLI_HEMORR   15495 non-null   object
 36  CLI_VAGAIS   15495 non-null   object
 37  CLI_MIOLIT   15494 non-null   object
 38  CLI_RENAL    15494 non-null   object
 39  CLI_OUTR_2   15493 non-null   object
 40  CLI_OUTR_3   6844 non-null    object
 41  CLI_TEMPO_   195157 non-null  object
 42  TP_ACIDENT   222849 non-null  object
 43  ANI_TIPO_1   9279 non-null    object
 44  ANI_SERPEN   28738 non-null   object
 45  ANI_ARANHA   33112 non-null   object
 46  ANI_LAGART   5164 non-null    object
 47  TRA_CLASSI   218123 non-null  object
 48  CON_SOROTE   222849 non-null  object
 49  NU_AMPOLAS   222858 non-null  int64
 50  NU_AMPOL_1   222858 non-null  int64
 51  NU_AMPOL_8   222858 non-null  int64
 52  NU_AMPOL_6   222858 non-null  int64
 53  NU_AMPOL_4   222858 non-null  int64
 54  NU_AMPO_7    222858 non-null  int64
 55  NU_AMPO_5    222858 non-null  int64
 56  NU_AMPOL_9   222858 non-null  int64
 57  NU_AMPOL_3   222858 non-null  int64
 58  COM_LOC      209695 non-null  object
 59  COM_SECUND   2669 non-null    object
 60  COM_NECROS   2666 non-null    object
 61  COM_COMPOR   2666 non-null    object
 62  COM_DEFICT   2665 non-null    object
 63  COM_APUTAC   2665 non-null    object
 64  COM_SISTEM   207942 non-null  object
 65  COM_RENAL    853 non-null     object
 66  COM_EDEMA    852 non-null     object
 67  COM_SEPTIC   852 non-null     object
 68  COM_CHOQUE   852 non-null     object
 69  DOENCA_TRA   212492 non-null  object
 70  EVOLUCAO     211354 non-null  object
 71  DT_OBITO     216 non-null     datetime64[ns]
 72  DT_ENCERRA   217816 non-null  datetime64[ns]
 73  DT_DIGITA    222858 non-null  datetime64[ns]
 74  NU_IDADE_N_  222858 non-null  int64
dtypes: datetime64[ns](7), float64(9), int64(16), object(43)
memory usage: 127.5+ MB

In [ ]:
#criando colunas com o dicionario de municipio
dados['ID_MUNICIP_nome'] = dados['ID_MUNICIP'].map(dicionario_municipios)
dados['ID_MN_RESI_nome'] = dados['ID_MUNICIP'].map(dicionario_municipios)
dados['ANT_MUNIC_nome'] = dados['ID_MUNICIP'].map(dicionario_municipios)

dados

Da mesma manneira, é possível alterar a codificação da OCUPAÇÃO

In [ ]:
ocupacao = pd.read_csv('https://raw.githubusercontent.com/andrejarenkow/Curso_SINAN_Udemy/main/dados/CBO2002%20-%20Ocupacao.csv')
ocupacao = ocupacao.set_index('CODIGO')
dicionario_ocupacao = ocupacao.to_dict()['TITULO']


dados['ID_OCUPA_N_nome'] = dados['ID_OCUPA_N'].map(dicionario_ocupacao)
dados

Chegou a hora de alterar também a codificação da UF para a sua respectiiva sigla, da mesma maneira como fizemos para os municípios.

In [25]:
tabela_uf = pd.read_csv('https://raw.githubusercontent.com/andrejarenkow/Curso_SINAN_Udemy/main/dados/cod_uf.csv')
tabela_uf = tabela_uf.set_index('Código UF')
dicionario_uf = tabela_uf.to_dict()['UF']


dados['SG_UF_nome'] = dados['SG_UF'].map(dicionario_uf)
dados['SG_UF_NOT_nome'] = dados['SG_UF_NOT'].map(dicionario_uf)
dados['ANT_UF_nome'] = dados['ANT_UF'].map(dicionario_uf)
dados

,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA,NU_IDADE_N_,ID_MUNICIP_nome,ID_MN_RESI_nome,ANT_MUNIC_nome,ID_OCUPA_N_nome,SG_UF_nome,SG_UF_NOT_nome,ANT_UF_nome
0,2017-01-01,201701,2017,29,291080,1381.0,2017-01-01,201701,2012.0,4004,M,Não se aplica,preta,10.0,29.0,291080.0,NaN,1.0,2017-01-01,NaN,2017-01-01,29.0,291080.0,NaN,Ignorado,tronco,Sim,Ignorado,Sim,Ignorado,Ignorado,Ignorado,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Ignorado,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaN,NaN,NaN,Ignorado,Cura,NaT,2017-02-02,2017-02-09,4,Feira de Santana,Feira de Santana,Feira de Santana,NaN,BA,BA,BA
1,2017-01-01,201701,2017,35,352620,1335.0,2017-01-01,201701,1980.0,4036,F,Ignorado,Ignorado,9.0,35.0,352620.0,NaN,1.0,2017-01-01,NaN,2017-01-01,35.0,352620.0,NaN,0 - 1h,Pé,Não,NaN,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Aranha,NaN,NaN,Ignorado,NaN,Ignorado,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ignorado,NaT,2017-01-02,2017-01-16,36,Juquitiba,Juquitiba,Juquitiba,NaN,SP,SP,SP
2,2017-01-01,201701,2017,13,130360,5584.0,2016-05-15,201620,1990.0,4025,F,Não,indígena,0.0,13.0,130360.0,NaN,1.0,2017-01-01,612005.0,2016-01-15,13.0,130360.0,NaN,12 e 24h,Pé,Sim,Sim,Sim,Sim,Sim,Não,NaN,Sim,Não,Sim,Sim,Não,Não,Não,NaN,Não realizado,Serpente,NaN,Botrópico,NaN,NaN,Grave,Sim,8,0,0,0,0,0,0,0,0,Sim,Sim,Sim,Não,Sim,Sim,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-01-01,2017-01-25,25,Santa Isabel do Rio Negro,Santa Isabel do Rio Negro,Santa Isabel do Rio Negro,Produtor agrícola polivalente,AM,AM,AM
3,2017-01-01,201701,2017,41,412010,1357.0,2017-01-01,201701,1954.0,4062,F,Não,branca,6.0,41.0,411770.0,NaN,1.0,2017-01-01,999993.0,2017-01-01,41.0,412010.0,NaN,0 - 1h,Pé,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-02-13,2017-02-17,62,Porto Amazonas,Porto Amazonas,Porto Amazonas,Aposentado/Pensionista,PR,PR,PR
4,2017-01-01,201701,2017,26,261160,1497.0,2017-01-01,201701,2013.0,4003,F,Não se aplica,Ignorado,10.0,26.0,260840.0,NaN,1.0,2017-01-01,NaN,2017-01-01,26.0,260840.0,NaN,0 - 1h,Pé,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-01-02,2017-03-28,3,Recife,Recife,Recife,NaN,PE,PE,PE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,2017-12-31,201801,2017,22,221050,NaN,2017-12-31,201801,2006.0,4011,M,Não se aplica,parda,3.0,22.0,220060.0,NaN,1.0,2017-12-31,999991.0,2017-12-31,22.0,220060.0,NaN,0 - 1h,Pé,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-12-31,2018-01-17,11,São Pedro do Piauí,São Pedro do Piauí,São Pedro do Piauí,Estudante,PI,PI,PI
222854,2017-12-31,201801,2017,22,221050,NaN,2017-12-31,201801,1982.0,4035,F,Não,parda,3.0,22.0,221050.0,NaN,1.0,2017-12-31,999992.0,2017-12-31,22.0,221050.0,NaN,0 - 1h,Mão,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-12-31,2018-01-17,35,São Pedro do Piauí,São Pedro do Piauí,São Pedro do Piauí,Dona de casa,PI,PI,PI
222855,2017-12-31,201801,2017,31,311680,1450.0,2017-12-31,201801,1962.0,4055,M,Não se aplica,parda,1.0,31.0,310620.0,NaN,1.0,2017-12-31,782305.0,2017-12-31,31.0,311680.0,NaN,1 - 3h,Dedo do Pé,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alterado,Serpente,NaN,Botrópico,NaN,NaN,Leve,Sim,3,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,NaN,NaT,2018-01-29,2018-01-29,55,Coluna,Coluna,Coluna,Motorista de carro de passeio,MG,MG,MG
222856,2017-12-31,201801,2017,41,410180,1356.0,2017-12-30,201752,1972.0,4045,F,Não,branca,9.0,41.0,410180.0,NaN,1.0,2017-12-31,NaN,2017-12-30,41.0,410180.0,NaN,12 e 24h,Cabeça,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Aranha,NaN,NaN,Loxoscelismo,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2018-02-10,2018-08-10,45,Araucária,Araucária,Araucária,NaN,PR,PR,PR
222857,2017-12-31,201801,2017,29,293330,1398.0,2017-12-31,201801,1998.0,4019,F,Ignorado,branca,NaN,29.0,290120.0,NaN,1.0,2017-12-31,NaN,2017-12-31,29.0,290120.0,NaN,NaN,Dedo do Pé,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Serpente,NaN,Laquético,NaN,NaN,Moderado,Sim,0,0,0,8,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaT,NaT,2019-10-18,19,Vitória da Conquista,Vitória da Conquista,Vitória da Conquista,NaN,BA,BA,BA

**Renomeando as colunas**


Outro problema bastante comum que sentimos ao visualizar um arquivo DBF do SINAN é o nome das colunas, que são outras codificações. Por isso, vamos renomeá-las, com uma função muito parecida com o que fizemos antes.

Primeiramente, vamos coletar o nome de todas.

In [26]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222858 entries, 0 to 222857
Data columns (total 82 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   DT_NOTIFIC       222858 non-null  datetime64[ns]
 1   SEM_NOT          222858 non-null  int64
 2   NU_ANO           222858 non-null  int64
 3   SG_UF_NOT        222858 non-null  int64
 4   ID_MUNICIP       222858 non-null  int64
 5   ID_REGIONA       212929 non-null  float64
 6   DT_SIN_PRI       222858 non-null  datetime64[ns]
 7   SEM_PRI          222858 non-null  int64
 8   ANO_NASC         219324 non-null  object
 9   NU_IDADE_N       222858 non-null  int64
 10  CS_SEXO          222858 non-null  object
 11  CS_GESTANT       222851 non-null  object
 12  CS_RACA          219292 non-null  object
 13  CS_ESCOL_N       199978 non-null  float64
 14  SG_UF            222784 non-null  float64
 15  ID_MN_RESI       222784 non-null  float64
 16  ID_RG_RESI       0 non-null       float64
 17  ID_PAIS          222857 non-null  float64
 18  DT_INVEST        222858 non-null  datetime64[ns]
 19  ID_OCUPA_N       113134 non-null  object
 20  ANT_DT_ACI       222849 non-null  datetime64[ns]
 21  ANT_UF           222849 non-null  float64
 22  ANT_MUNIC_       222849 non-null  float64
 23  ANT_LOCALI       0 non-null       float64
 24  ANT_TEMPO_       216993 non-null  object
 25  ANT_LOCA_1       222849 non-null  object
 26  MCLI_LOCAL       221008 non-null  object
 27  CLI_DOR          207069 non-null  object
 28  CLI_EDEMA        207061 non-null  object
 29  CLI_EQUIMO       207041 non-null  object
 30  CLI_NECROS       207040 non-null  object
 31  CLI_LOCAL_       207027 non-null  object
 32  CLI_LOCA_1       26503 non-null   object
 33  MCLI_SIST        218133 non-null  object
 34  CLI_NEURO        15495 non-null   object
 35  CLI_HEMORR       15495 non-null   object
 36  CLI_VAGAIS       15495 non-null   object
 37  CLI_MIOLIT       15494 non-null   object
 38  CLI_RENAL        15494 non-null   object
 39  CLI_OUTR_2       15493 non-null   object
 40  CLI_OUTR_3       6844 non-null    object
 41  CLI_TEMPO_       195157 non-null  object
 42  TP_ACIDENT       222849 non-null  object
 43  ANI_TIPO_1       9279 non-null    object
 44  ANI_SERPEN       28738 non-null   object
 45  ANI_ARANHA       33112 non-null   object
 46  ANI_LAGART       5164 non-null    object
 47  TRA_CLASSI       218123 non-null  object
 48  CON_SOROTE       222849 non-null  object
 49  NU_AMPOLAS       222858 non-null  int64
 50  NU_AMPOL_1       222858 non-null  int64
 51  NU_AMPOL_8       222858 non-null  int64
 52  NU_AMPOL_6       222858 non-null  int64
 53  NU_AMPOL_4       222858 non-null  int64
 54  NU_AMPO_7        222858 non-null  int64
 55  NU_AMPO_5        222858 non-null  int64
 56  NU_AMPOL_9       222858 non-null  int64
 57  NU_AMPOL_3       222858 non-null  int64
 58  COM_LOC          209695 non-null  object
 59  COM_SECUND       2669 non-null    object
 60  COM_NECROS       2666 non-null    object
 61  COM_COMPOR       2666 non-null    object
 62  COM_DEFICT       2665 non-null    object
 63  COM_APUTAC       2665 non-null    object
 64  COM_SISTEM       207942 non-null  object
 65  COM_RENAL        853 non-null     object
 66  COM_EDEMA        852 non-null     object
 67  COM_SEPTIC       852 non-null     object
 68  COM_CHOQUE       852 non-null     object
 69  DOENCA_TRA       212492 non-null  object
 70  EVOLUCAO         211354 non-null  object
 71  DT_OBITO         216 non-null     datetime64[ns]
 72  DT_ENCERRA       217816 non-null  datetime64[ns]
 73  DT_DIGITA        222858 non-null  datetime64[ns]
 74  NU_IDADE_N_      222858 non-null  int64
 75  ID_MUNICIP_nome  222858 non-null  object
 76  ID_MN_RESI_nome  222858 non-null  object
 77  ANT_MUNIC_nome   222858 non-null  object
 78  ID_OCUPA_N_nome  49439 non-null   object
 79  SG_UF_nome       222784 non-null  object
 80  SG_UF_NOT_nome   222858 non-null  object
 81  ANT_UF_nome      222849 non-null  object
dtypes: datetime64[ns](7), float64(9), int64(16), object(50)
memory usage: 139.4+ MB

Agora, copiamos e colamos esta lista, e vamos adaptando de maneira a criar um dicionário (de novo).

In [27]:
dicionario_colunas= {'DT_NOTIFIC':'Data da notificação',
                     'SEM_NOT':'Semana da notificação',
                     'NU_ANO':'Ano da notificação',
                     'SG_UF_NOT':'UF de notificação',
                     'ID_MUNICIP':'Código Município de notificação',
                     'ID_REGIONA':'Regional de Notificação',
                     'DT_SIN_PRI':'Data de início dos sintomas',
                     'SEM_PRI':'Semana de início dos sintomas',
                     'DT_NASC':'Data de Nascimento',
                     'NU_IDADE_N':'Idade',
                      'CS_SEXO':'Sexo',
                      'CS_GESTANT':"Gestante",
                      'CS_RACA':'Raça',
                      'CS_ESCOL_N':'Escolaridade',
                      'SG_UF':'UF de Residência',
                      'ID_MN_RESI':'Código Município de Residência',
                      'ID_RG_RESI':'Regional de Residência',
                      'ID_PAIS':'País de Residência',
                      'DT_INVEST':'Data da investigação',
                      'ID_OCUPA_N':'Ocupação',
                      'ANT_DT_ACI':'Data do acidente',
                      'ANT_UF':'UF do acidente',
                      'ANT_MUNIC_':'Código Município de ocorrência do acidente',
                      'ANT_LOCALI':'Localidade da ocorrência',
                      'ANT_ZONA':'Zona de ocorrência',
                      'ANT_TEMPO_':'Tempo decorrido picada/atendimento',
                      'ANT_LOCA_1':'Local da picada',
                      'MCLI_LOCAL':'Manifestações locais',
                      'CLI_DOR':'Manifestações locais - Dor',
                      'CLI_EDEMA':'Manifestações locais - Edema',
                      'CLI_EQUIMO':'Manifestações locais - Esquimose',
                      'CLI_NECROS':'Manifestações locais - Necrose',
                      'CLI_LOCAL_':'Manifestações locais - Outras',
                      'CLI_LOCA_1':'Manifestações locais - Outras - especificada',
                      'MCLI_SIST':'Manifestações sistêmicas',
                      'CLI_NEURO':'Manifestações sistêmicas - Neuroparalíticas (ptose, palpebral, turvação visual',
                      'CLI_HEMORR':'Manifestações sistêmicas - Hemorrágicas (gengivorragia, outros sangramentos)',
                      'CLI_VAGAIS':'Manifestações sistêmicas - Vagais (vômitos/ diarreias)',
                      'CLI_MIOLIT':'Manifestações sistêmicas - Miolíficas/hemolíticas (mialgia, anemia, urina escura)',
                      'CLI_RENAL':'Manifestações sistêmicas - Renais (oligúria/anúria)',
                      'CLI_OUTR_2':'Manifestações sistêmicas - Outras',
                      'CLI_OUTR_3':'Manifestações sistêmicas - Outras especificada',
                      'CLI_TEMPO_':'Tempo de coagulação',
                      'TP_ACIDENT':'Tipo de acidente',
                      'ANI_TIPO_1':'Tipo de acidente - outros',
                      'ANI_SERPEN':'Serpente - tipo de acidente',
                      'ANI_ARANHA':'Aranha - tipo de acidente',
                      'ANI_LAGART':'Lagarta - tipo de acidente',
                      'TRA_CLASSI':'Classificação do caso',
                      'CON_SOROTE':'Soroterapia',
                      'NU_AMPOLAS':'Soroterapia - Número de ampolas de soro antibrotópico (SAB)',
                      'NU_AMPOL_1':'Soroterapia - Número de ampolas de soro antivrotálico (SAC)',
                      'NU_AMPOL_8':'Soroterapia - Número de ampolas de soro antiaracnídico (SAAr)',
                      'NU_AMPOL_6':'Soroterapia - Número de ampolas de soro antibrotópico-laquético (SABL)',
                      'NU_AMPOL_4':'Soroterapia - Número de ampolas de soro antielapídico (SAEL)',
                      'NU_AMPO_7':'Soroterapia - Número de ampolas de soro antiloxoscélico (SALox)',
                      'NU_AMPO_5':'Soroterapia - Número de ampolas de soro antibrotópico-crotálico (SABC)',
                      'NU_AMPOL_9':'Soroterapia - Número de ampolas de soro antiescorpiônico (SAEsc)',
                      'NU_AMPOL_3':'Soroterapia - Número de ampolas de soro antilonômico (SALon)',
                      'COM_LOC':'Complicações locais',
                      'COM_SECUND':'Complicações locais - Infecção secundária',
                      'COM_NECROS':'Complicações locais - Necrose extensa',
                      'COM_COMPOR':'Complicações locais - Síndrome comportamental',
                      'COM_DEFICT':'Complicações locais - Déficit Funcional ',
                      'COM_APUTAC':'Complicações locais - Amputação ',
                      'COM_SISTEM':'Complicações sistêmicas',
                      'COM_RENAL':'Complicações sistêmicas - Insuficiência renal ',
                      'COM_EDEMA':'Complicações sistêmicas - Insuficiência Respiratória/Edema Pulmonar Agudo ',
                      'COM_SEPTIC':'Complicações sistêmicas - Septicemia ',
                      'COM_CHOQUE':'Complicações sistêmicas - Choque ',
                      'DOENCA_TRA':'Acidente relacionado ao trabalho',
                      'EVOLUCAO':'Evolução do caso',
                      'DT_OBITO':'Data do óbito',
                      'DT_ENCERRA':'Data do encerramento',
                      'DT_DIGITA':'Data de digitação',
                      'ID_MUNICIP_nome':'Município de notificação',
                      'ID_MN_RESI_nome':'Município de Residência',
                      'ANT_MUNIC__nome':'Município de ocorrência do acidente'}

Agora que temos o dicionário das colunas COMPPLETO, utilizamos o comando de RENAME no nosso DataFrame, assim teremos ele organizado de maneira mais adequada

In [29]:
dados_final = dados.rename(columns  = dicionario_colunas)

**Exportação para CSV**

Vamos exporta o nosso DataFrame final para o Excl, caso haja a necessidade de visualizar os dados no programa Esta operação demora um pouco.

In [30]:
dados_final.to_csv('dados_peconhentos.csv', index=False, sep=';')